# Webapp handler maps any URI of the form /* to the controller.dispatcher module

application: agilearticle
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: controller.dispatcher.application
